from ukupacha.Utils import is_dict
from blockdiag import parser, builder, drawer


def graph2blockdiag(regs, pdb):
    """
    Recursive algorithm to parse the graph to a blockdiag structure.
    """
    reg = regs[0]
    parent = list(reg.keys())[0]
    regs = reg.get(parent)
    if regs is None:
        return f"'{parent}\n{pdb}';\n"
    output = ""
    for sub_reg in regs:
        db = sub_reg["DB"]
        for node in sub_reg["TABLES"]:
            out = graph2blockdiag([node], db)
            output += f" '{parent}\n{pdb}' -> {out}"
    return output


def model2diag(model: dict):
    """
    Given the model dict, takes the graph and the initial db to
    call grap2blockdiag
    """
    graph = model["GRAPH"]
    db = model["CHECKPOINT"]["DB"]
    out = graph2blockdiag(graph, db)
    output = "diagram { "+out+" }"
    return output


def diag2file(diag, filename, fmt):
    """
    Function to save the diagram in a file.

    Parameters
    ------------
    diag:str
        String with the diagram generated by model2diag
    filename:str
        file to save the diagram
    fmt:str
        format of the file, supported "SVG", "PNG" and "PDF"
    """
    tree = parser.parse_string(diag)
    diagram = builder.ScreenNodeBuilder.build(tree)
    draw = drawer.DiagramDraw(fmt, diagram, filename=filename)
    draw.draw()
    draw.save()
